Vul_Path
"src/fides/api/service/connectors/saas/connector_registry_service.py:[66,96]:_load_connector_templates"
"src/fides/api/service/connectors/saas/connector_registry_service.py:[142,160]:_register_template"
"src/fides/api/service/connectors/saas/connector_registry_service.py:[164,265]:save_template"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[467,479]:complete_connector_template"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[610,625]:connector_template_duplicate_configs"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[595,608]:connector_template_duplicate_datasets"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[611,624]:connector_template_duplicate_icons"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[509,521]:connector_template_invalid_config"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[551,563]:connector_template_invalid_dataset"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[482,492]:connector_template_missing_config"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[524,534]:connector_template_missing_dataset"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[566,576]:connector_template_no_icon"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[495,506]:connector_template_wrong_contents_config"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[537,548]:connector_template_wrong_contents_dataset"
"tests/ops/api/v1/endpoints/test_saas_config_endpoints.py:[626,645]:test_register_connector_template_wrong_scope"
"tests/ops/models/test_custom_connector_template.py:[9,39]:test_create_custom_connector_template"
"tests/ops/service/connectors/test_connector_template_loaders.py:[111,123]:replaceable_planet_express_zip"
"tests/ops/service/connectors/test_connector_template_loaders.py:[224,259]:test_custom_connector_save_template"
"tests/ops/service/connectors/test_connector_template_loaders.py:[163,191]:test_custom_connector_template_loader"
"tests/ops/service/connectors/test_connector_template_loaders.py:[141,158]:test_custom_connector_template_loader_invalid_template"
"tests/ops/service/connectors/test_connector_template_loaders.py:[134,136]:test_custom_connector_template_loader_no_templates"
"tests/ops/service/connectors/test_connector_template_loaders.py:[196,219]:test_loaders_have_separate_instances"